application: sfgeocoder
version: 1
runtime: python
api_version: 1

handlers:
- url: /jquery
  static_dir: jquery
- url: /(.*\.(gif|png|jpg|css))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|css))
- url: /
  script: app.py
- url: /image.*
  script: app.py
- url: /geocode.*
  script: app.py
- url: /upload.*
  script: app.py
- url: /upload_form.*
  script: app.py


builtins:
- remote_api: on
- datastore_admin: on
