application: labeler
version: 1
runtime: python
api_version: 1

handlers:
- url: /jquery
  static_dir: jquery
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))
- url: /.*
  script: app.py


builtins:
- remote_api: on
