application: sf-viewer

version: 2013-01-14
runtime: python
api_version: 1

handlers:
- url: /jquery
  static_dir: jquery
- url: /dots
  static_dir: dots
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /
  static_files: viewer.html
  upload: viewer.html
- url: /about
  static_files: about.html
  upload: about.html
- url: /feedback
  static_files: feedback.html
  upload: feedback.html
- url: /upload
  script: app.py
- url: /lat-lons.js
  static_files: lat-lons.js
  upload: lat-lons.js
- url: /thumb/.*
  script: app.py
- url: /(.*\.(gif|png|jpg|css|js|zip))
  static_files: \1
  upload: (.*\.(gif|png|jpg|css|js|zip))
- url: .*
  script: app.py


builtins:
- remote_api: on
- datastore_admin: on
